// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: example.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 地址信息
// [EN] Address information
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Province      string                 `protobuf:"bytes,1,opt,name=province,proto3" json:"province" validate:"required,min=2,max=50" gorm:"type:varchar(50);not null"`                // 省份 | [EN] Province
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city" validate:"required,min=2,max=50" gorm:"type:varchar(50);not null"`                        // 城市 | [EN] City
	Street        string                 `protobuf:"bytes,3,opt,name=street,proto3" json:"street" validate:"required,min=5,max=200" gorm:"type:varchar(200);not null"`                  // 街道地址 | [EN] Street address
	PostalCode    string                 `protobuf:"bytes,4,opt,name=postal_code,json=postalCode,proto3" json:"postal_code" validate:"omitempty,len=6,numeric" gorm:"type:varchar(10)"` // 邮政编码 | [EN] Postal code
	IsDefault     bool                   `protobuf:"varint,5,opt,name=is_default,json=isDefault,proto3" json:"is_default" gorm:"type:boolean;default:false"`                            // 是否默认地址 | [EN] Is default address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

// 用户配置
// [EN] User settings
type UserSettings struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Language            string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language" validate:"oneof=zh-CN en-US ja-JP" gorm:"type:varchar(10);default:zh-CN"`           // 语言 | [EN] Language
	Theme               string                 `protobuf:"bytes,2,opt,name=theme,proto3" json:"theme" validate:"oneof=light dark auto" gorm:"type:varchar(10);default:light"`                   // 主题 | [EN] Theme
	NotificationEnabled bool                   `protobuf:"varint,3,opt,name=notification_enabled,json=notificationEnabled,proto3" json:"notification_enabled" gorm:"type:boolean;default:true"` // 是否启用通知 | [EN] Notification enabled
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UserSettings) Reset() {
	*x = UserSettings{}
	mi := &file_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettings) ProtoMessage() {}

func (x *UserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettings.ProtoReflect.Descriptor instead.
func (*UserSettings) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{1}
}

func (x *UserSettings) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UserSettings) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *UserSettings) GetNotificationEnabled() bool {
	if x != nil {
		return x.NotificationEnabled
	}
	return false
}

// 用户信息
// [EN] User information
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id" validate:"required,uuid" gorm:"primaryKey;type:uuid;comment:用户ID" bson:"_id,omitempty"`                                                                   // 用户ID | [EN] User ID
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username" validate:"required,min=3,max=50,alphanum" gorm:"uniqueIndex;type:varchar(50);not null;comment:用户名" bson:"username"`                           // 用户名 | [EN] Username
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email" validate:"required,email" gorm:"uniqueIndex;type:varchar(100);not null;comment:邮箱" bson:"email"`                                                    // 邮箱 | [EN] Email
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"-" validate:"required,min=8,max=100" gorm:"type:varchar(255);not null;comment:密码" bson:"password"`                                                      // 密码 | [EN] Password
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone" validate:"omitempty,len=11,numeric" gorm:"index;type:varchar(20);comment:手机号" bson:"phone,omitempty"`                                               // 手机号 | [EN] Phone
	Age           int32                  `protobuf:"varint,6,opt,name=age,proto3" json:"age,omitempty" validate:"omitempty,gte=0,lte=150" gorm:"type:int;comment:年龄" bson:"age,omitempty"`                                                          // 年龄 | [EN] Age
	Gender        string                 `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender" validate:"omitempty,oneof=male female other" gorm:"type:varchar(10);comment:性别" bson:"gender,omitempty"`                                          // 性别 | [EN] Gender
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status" validate:"required,oneof=active inactive suspended" gorm:"type:varchar(20);default:active;index;comment:状态" bson:"status"`                        // 状态 | [EN] Status
	Addresses     []*Address             `protobuf:"bytes,9,rep,name=addresses,proto3" json:"addresses" validate:"omitempty,dive" gorm:"foreignKey:UserID" bson:"addresses,omitempty"`                                                              // 地址列表 | [EN] Address list
	Settings      *UserSettings          `protobuf:"bytes,10,opt,name=settings,proto3" json:"settings" validate:"omitempty" gorm:"embedded;embeddedPrefix:settings_" bson:"settings,omitempty"`                                                     // 用户设置 | [EN] User settings
	Metadata      map[string]string      `protobuf:"bytes,11,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value" gorm:"type:jsonb;comment:元数据" bson:"metadata,omitempty"` // 元数据 | [EN] Metadata
	Roles         []string               `protobuf:"bytes,12,rep,name=roles,proto3" json:"roles" validate:"omitempty,dive,oneof=admin user guest" gorm:"type:text[];comment:角色" bson:"roles,omitempty"`                                             // 角色列表 | [EN] Roles
	AvatarUrl     string                 `protobuf:"bytes,13,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty" validate:"omitempty,url" gorm:"type:varchar(500);comment:头像" bson:"avatar_url,omitempty"`                       // 头像URL | [EN] Avatar URL
	Bio           string                 `protobuf:"bytes,14,opt,name=bio,proto3" json:"bio,omitempty" validate:"omitempty,max=500" gorm:"type:text;comment:简介" bson:"bio,omitempty"`                                                               // 个人简介 | [EN] Bio
	Balance       float64                `protobuf:"fixed64,15,opt,name=balance,proto3" json:"balance" validate:"gte=0" gorm:"type:decimal(10,2);default:0;comment:余额" bson:"balance"`                                                              // 账户余额 | [EN] Balance
	IsVerified    bool                   `protobuf:"varint,16,opt,name=is_verified,json=isVerified,proto3" json:"is_verified" gorm:"type:boolean;default:false;comment:已验证" bson:"is_verified"`                                                     // 是否已验证 | [EN] Is verified
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *User) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *User) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *User) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *User) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *User) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *User) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *User) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *User) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *User) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

// 创建用户请求
// [EN] Create user request
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty" validate:"required,min=3,max=50,alphanum"` // 用户名 | [EN] Username
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty" validate:"required,email"`                       // 邮箱 | [EN] Email
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty" validate:"required,min=8,max=100"`         // 密码 | [EN] Password
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty" validate:"omitempty,len=11,numeric"`             // 手机号 | [EN] Phone
	Age           int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty" validate:"omitempty,gte=0,lte=150"`                 // 年龄 | [EN] Age
	Addresses     []*Address             `protobuf:"bytes,6,rep,name=addresses,proto3" json:"addresses,omitempty" validate:"omitempty,dive"`               // 地址列表 | [EN] Address list
	Settings      *UserSettings          `protobuf:"bytes,7,opt,name=settings,proto3" json:"settings,omitempty" validate:"omitempty"`                      // 用户设置 | [EN] User settings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{3}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateUserRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreateUserRequest) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *CreateUserRequest) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// 创建用户响应
// [EN] Create user response
type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user"`       // 用户信息 | [EN] User information
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message"` // 响应消息 | [EN] Response message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_example_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 查询用户请求
// [EN] Get user request
type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" validate:"required,uuid"` // 用户ID | [EN] User ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_example_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 查询用户响应
// [EN] Get user response
type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user"` // 用户信息 | [EN] User information
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_example_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

// 用户列表请求
// [EN] List users request
type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty" validate:"omitempty,gte=1,lte=100"`                 // 每页数量 | [EN] Page size
	PageNum       int32                  `protobuf:"varint,2,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty" validate:"omitempty,gte=1"`                            // 页码 | [EN] Page number
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty" validate:"omitempty,oneof=active inactive suspended"`                    // 状态过滤 | [EN] Status filter
	Keyword       string                 `protobuf:"bytes,4,opt,name=keyword,proto3" json:"keyword,omitempty" validate:"omitempty,min=1,max=50"`                                     // 搜索关键词 | [EN] Search keyword
	SortBy        string                 `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty" validate:"omitempty,oneof=created_at updated_at username"` // 排序字段 | [EN] Sort by
	SortOrder     string                 `protobuf:"bytes,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty" validate:"omitempty,oneof=asc desc"`              // 排序方向 | [EN] Sort order
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_example_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{7}
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListUsersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListUsersRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListUsersRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListUsersRequest) GetSortOrder() string {
	if x != nil {
		return x.SortOrder
	}
	return ""
}

// 用户列表响应
// [EN] List users response
type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users"`                        // 用户列表 | [EN] User list
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total"`                       // 总数 | [EN] Total count
	PageNum       int32                  `protobuf:"varint,3,opt,name=page_num,json=pageNum,proto3" json:"page_num"`    // 当前页码 | [EN] Current page
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size"` // 每页数量 | [EN] Page size
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_example_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{8}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUsersResponse) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListUsersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 更新用户请求
// [EN] Update user request
type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" validate:"required,uuid"`                                // 用户ID | [EN] User ID
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty" validate:"omitempty,min=3,max=50,alphanum"`  // 用户名 | [EN] Username
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty" validate:"omitempty,email"`                        // 邮箱 | [EN] Email
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty" validate:"omitempty,len=11,numeric"`               // 手机号 | [EN] Phone
	Age           int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty" validate:"omitempty,gte=0,lte=150"`                   // 年龄 | [EN] Age
	AvatarUrl     string                 `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty" validate:"omitempty,url"` // 头像URL | [EN] Avatar URL
	Bio           string                 `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty" validate:"omitempty,max=500"`                          // 个人简介 | [EN] Bio
	Settings      *UserSettings          `protobuf:"bytes,8,opt,name=settings,proto3" json:"settings,omitempty" validate:"omitempty"`                        // 用户设置 | [EN] User settings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_example_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateUserRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *UpdateUserRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UpdateUserRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UpdateUserRequest) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// 更新用户响应
// [EN] Update user response
type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user"`       // 用户信息 | [EN] User information
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message"` // 响应消息 | [EN] Response message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_example_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UpdateUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 删除用户请求
// [EN] Delete user request
type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" validate:"required,uuid"`                                // 用户ID | [EN] User ID
	HardDelete    bool                   `protobuf:"varint,2,opt,name=hard_delete,json=hardDelete,proto3" json:"hard_delete,omitempty" validate:"omitempty"` // 是否硬删除 | [EN] Hard delete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_example_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteUserRequest) GetHardDelete() bool {
	if x != nil {
		return x.HardDelete
	}
	return false
}

// 删除用户响应
// [EN] Delete user response
type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message"` // 响应消息 | [EN] Response message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_example_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 批量操作请求
// [EN] Batch operation request
type BatchOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty" validate:"required,min=1,dive,uuid"`                           // 用户ID列表 | [EN] User ID list
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty" validate:"required,oneof=delete activate suspend"` // 操作类型 | [EN] Operation type
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchOperationRequest) Reset() {
	*x = BatchOperationRequest{}
	mi := &file_example_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOperationRequest) ProtoMessage() {}

func (x *BatchOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOperationRequest.ProtoReflect.Descriptor instead.
func (*BatchOperationRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{13}
}

func (x *BatchOperationRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *BatchOperationRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

// 批量操作响应
// [EN] Batch operation response
type BatchOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AffectedCount int32                  `protobuf:"varint,1,opt,name=affected_count,json=affectedCount,proto3" json:"affected_count"` // 影响数量 | [EN] Affected count
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`                                   // 响应消息 | [EN] Response message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchOperationResponse) Reset() {
	*x = BatchOperationResponse{}
	mi := &file_example_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOperationResponse) ProtoMessage() {}

func (x *BatchOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOperationResponse.ProtoReflect.Descriptor instead.
func (*BatchOperationResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{14}
}

func (x *BatchOperationResponse) GetAffectedCount() int32 {
	if x != nil {
		return x.AffectedCount
	}
	return 0
}

func (x *BatchOperationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 修改密码请求
// [EN] Change password request
type ChangePasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty" validate:"required,uuid"`                                           // 用户ID | [EN] User ID
	OldPassword     string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty" validate:"required,min=8,max=100"`                   // 旧密码 | [EN] Old password
	NewPassword     string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty" validate:"required,min=8,max=100"`                   // 新密码 | [EN] New password
	ConfirmPassword string                 `protobuf:"bytes,4,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty" validate:"required,eqfield=NewPassword"` // 确认密码 | [EN] Confirm password
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_example_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{15}
}

func (x *ChangePasswordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetConfirmPassword() string {
	if x != nil {
		return x.ConfirmPassword
	}
	return ""
}

// 修改密码响应
// [EN] Change password response
type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message"` // 响应消息 | [EN] Response message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_example_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_example_proto_rawDescGZIP(), []int{16}
}

func (x *ChangePasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_example_proto protoreflect.FileDescriptor

const file_example_proto_rawDesc = "" +
	"\n" +
	"\rexample.proto\x12\aexample\"\x91\x01\n" +
	"\aAddress\x12\x1a\n" +
	"\bprovince\x18\x01 \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x16\n" +
	"\x06street\x18\x03 \x01(\tR\x06street\x12\x1f\n" +
	"\vpostal_code\x18\x04 \x01(\tR\n" +
	"postalCode\x12\x1d\n" +
	"\n" +
	"is_default\x18\x05 \x01(\bR\tisDefault\"s\n" +
	"\fUserSettings\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x14\n" +
	"\x05theme\x18\x02 \x01(\tR\x05theme\x121\n" +
	"\x14notification_enabled\x18\x03 \x01(\bR\x13notificationEnabled\"\x97\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x10\n" +
	"\x03age\x18\x06 \x01(\x05R\x03age\x12\x16\n" +
	"\x06gender\x18\a \x01(\tR\x06gender\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12.\n" +
	"\taddresses\x18\t \x03(\v2\x10.example.AddressR\taddresses\x121\n" +
	"\bsettings\x18\n" +
	" \x01(\v2\x15.example.UserSettingsR\bsettings\x127\n" +
	"\bmetadata\x18\v \x03(\v2\x1b.example.User.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05roles\x18\f \x03(\tR\x05roles\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\r \x01(\tR\tavatarUrl\x12\x10\n" +
	"\x03bio\x18\x0e \x01(\tR\x03bio\x12\x18\n" +
	"\abalance\x18\x0f \x01(\x01R\abalance\x12\x1f\n" +
	"\vis_verified\x18\x10 \x01(\bR\n" +
	"isVerified\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xec\x01\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x10\n" +
	"\x03age\x18\x05 \x01(\x05R\x03age\x12.\n" +
	"\taddresses\x18\x06 \x03(\v2\x10.example.AddressR\taddresses\x121\n" +
	"\bsettings\x18\a \x01(\v2\x15.example.UserSettingsR\bsettings\"Q\n" +
	"\x12CreateUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.example.UserR\x04user\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x0fGetUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.example.UserR\x04user\"\xb4\x01\n" +
	"\x10ListUsersRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x19\n" +
	"\bpage_num\x18\x02 \x01(\x05R\apageNum\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\akeyword\x18\x04 \x01(\tR\akeyword\x12\x17\n" +
	"\asort_by\x18\x05 \x01(\tR\x06sortBy\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\tR\tsortOrder\"\x86\x01\n" +
	"\x11ListUsersResponse\x12#\n" +
	"\x05users\x18\x01 \x03(\v2\r.example.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x19\n" +
	"\bpage_num\x18\x03 \x01(\x05R\apageNum\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xe1\x01\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x10\n" +
	"\x03age\x18\x05 \x01(\x05R\x03age\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\x12\x10\n" +
	"\x03bio\x18\a \x01(\tR\x03bio\x121\n" +
	"\bsettings\x18\b \x01(\v2\x15.example.UserSettingsR\bsettings\"Q\n" +
	"\x12UpdateUserResponse\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.example.UserR\x04user\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vhard_delete\x18\x02 \x01(\bR\n" +
	"hardDelete\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"G\n" +
	"\x15BatchOperationRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\"Y\n" +
	"\x16BatchOperationResponse\x12%\n" +
	"\x0eaffected_count\x18\x01 \x01(\x05R\raffectedCount\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa1\x01\n" +
	"\x15ChangePasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fold_password\x18\x02 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\x12)\n" +
	"\x10confirm_password\x18\x04 \x01(\tR\x0fconfirmPassword\"2\n" +
	"\x16ChangePasswordResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB6Z4github.com/kamalyes/protoc-go-inject-tag/examples/pbb\x06proto3"

var (
	file_example_proto_rawDescOnce sync.Once
	file_example_proto_rawDescData []byte
)

func file_example_proto_rawDescGZIP() []byte {
	file_example_proto_rawDescOnce.Do(func() {
		file_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)))
	})
	return file_example_proto_rawDescData
}

var file_example_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_example_proto_goTypes = []any{
	(*Address)(nil),                // 0: example.Address
	(*UserSettings)(nil),           // 1: example.UserSettings
	(*User)(nil),                   // 2: example.User
	(*CreateUserRequest)(nil),      // 3: example.CreateUserRequest
	(*CreateUserResponse)(nil),     // 4: example.CreateUserResponse
	(*GetUserRequest)(nil),         // 5: example.GetUserRequest
	(*GetUserResponse)(nil),        // 6: example.GetUserResponse
	(*ListUsersRequest)(nil),       // 7: example.ListUsersRequest
	(*ListUsersResponse)(nil),      // 8: example.ListUsersResponse
	(*UpdateUserRequest)(nil),      // 9: example.UpdateUserRequest
	(*UpdateUserResponse)(nil),     // 10: example.UpdateUserResponse
	(*DeleteUserRequest)(nil),      // 11: example.DeleteUserRequest
	(*DeleteUserResponse)(nil),     // 12: example.DeleteUserResponse
	(*BatchOperationRequest)(nil),  // 13: example.BatchOperationRequest
	(*BatchOperationResponse)(nil), // 14: example.BatchOperationResponse
	(*ChangePasswordRequest)(nil),  // 15: example.ChangePasswordRequest
	(*ChangePasswordResponse)(nil), // 16: example.ChangePasswordResponse
	nil,                            // 17: example.User.MetadataEntry
}
var file_example_proto_depIdxs = []int32{
	0,  // 0: example.User.addresses:type_name -> example.Address
	1,  // 1: example.User.settings:type_name -> example.UserSettings
	17, // 2: example.User.metadata:type_name -> example.User.MetadataEntry
	0,  // 3: example.CreateUserRequest.addresses:type_name -> example.Address
	1,  // 4: example.CreateUserRequest.settings:type_name -> example.UserSettings
	2,  // 5: example.CreateUserResponse.user:type_name -> example.User
	2,  // 6: example.GetUserResponse.user:type_name -> example.User
	2,  // 7: example.ListUsersResponse.users:type_name -> example.User
	1,  // 8: example.UpdateUserRequest.settings:type_name -> example.UserSettings
	2,  // 9: example.UpdateUserResponse.user:type_name -> example.User
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_example_proto_init() }
func file_example_proto_init() {
	if File_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_proto_rawDesc), len(file_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_example_proto_goTypes,
		DependencyIndexes: file_example_proto_depIdxs,
		MessageInfos:      file_example_proto_msgTypes,
	}.Build()
	File_example_proto = out.File
	file_example_proto_goTypes = nil
	file_example_proto_depIdxs = nil
}
