name: Test

on:
  push:
    branches: [ master, develop ]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches: [ master, develop ]
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

jobs:
  Build:
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x]
        platform: [ubuntu-latest, windows-latest, macos-latest, macos-14]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@v1.12.0 # 指定版本
      - name: Test
        run: gotestsum -f testname -- ./... -race -count=1 -shuffle=on
        continue-on-error: true

      - name: Test
        run: gotestsum -f testname -- ./... -race -count=1 -coverprofile=coverage.txt -covermode=atomic -shuffle=on
        continue-on-error: true
      - name: Upload coverage reports to Codecov
        if: ${{ matrix.platform == 'ubuntu-latest' && matrix.go-version == '1.22.x' }}
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unittests
          slug: kamalyes/protoc-go-inject-tag
